# Dev overlay. CI writes the immutable image digest here.
image:
  repository: ghcr.io/arthur-16/ArgoDemo
  digest: "sha256:REPLACED_BY_CI"

replicaCount: 2

# For Minikube demo with NGINX ingress add-on
ingress:
  enabled: true
  className: nginx                  # minikube addon = nginx
  annotations: {}
  # If you DON'T set hosts below, the template will default to: "<release>.local"
  # Optionally set a baseDomain to change that default to "<release>.<baseDomain>"
  baseDomain: local                 # results in "<release>.local"
  # hosts:                          # Optional explicit override example
  #   - host: demo.local
  #     paths:
  #       - path: /
  #         pathType: Prefix

  tls:
    enabled: false                  # set true if you add a TLS secret
    secretName: ""                  # optional; if empty, defaults to "<fullname>-tls"

service:
  type: ClusterIP
  port: 80
containerPort: 8080
