replicaCount: 2

# Use working public image (CI can update this later)
image:
  repository: nginx
  tag: "1.21-alpine"
  digest: ""  # CI will populate this when your custom image is built
  pullPolicy: IfNotPresent

demo:
  message: "GitOps Demo - Development Environment"
  version: "dev-v1.1-working"
  environment: "development"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: demo-0-dev.local
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 60m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60

healthcheck:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10