<<<<<<< HEAD
# Development Environment - Optimized for Quick Changes
replicaCount: 2

demo:
  message: "GitOps Demo - Development Environment 🚀"
  version: "dev-v1.0"
  environment: "development"

=======
# Dev overlay. CI writes the immutable image digest here.
image:
  repository: ghcr.io/arthur-16/argorepo
  digest: "sha256:19fbd935e20196c9c1583e961affc5faa47c8728f2e7bb755ab223de67c8ad56"
replicaCount: 2
# For Minikube demo with NGINX ingress add-on
>>>>>>> d69baaabff67a3ff9d3f31d9e8f6eb8a405be7e5
ingress:
  host: demo-dev.local

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 60m
    memory: 64Mi

# Enable autoscaling for dev environment demos
autoscaling:
  enabled: true
<<<<<<< HEAD
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
=======
  className: nginx
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix
>>>>>>> d69baaabff67a3ff9d3f31d9e8f6eb8a405be7e5
