# Dev overlay. CI writes the immutable image digest here.
image:
  repository: ghcr.io/arthur-16/argorepo
  digest: "sha256:19fbd935e20196c9c1583e961affc5faa47c8728f2e7bb755ab223de67c8ad56"
replicaCount: 2
# For Minikube demo with NGINX ingress add-on
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix
