# Staging Environment - Working Configuration
replicaCount: 3
<<<<<<< HEAD

# Use working public image (CI can update this later)
image:
  repository: nginx
  tag: "1.21-alpine"
  digest: ""  # CI will populate this when your custom image is built
  pullPolicy: IfNotPresent

demo:
  message: "GitOps Demo - Staging Environment"
  version: "staging-v1.1-working"
  environment: "staging"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: demo-0-staging.local
  path: /
  pathType: Prefix

=======
demo:
  message: "GitOps Demo - Staging Build 57f80b655c46"
  version: "staging-v1.1-57f80b655c46"
  environment: "staging"
ingress:
  host: demo-staging.local
>>>>>>> 5acf6c8df5cce68fce1994debbd1a914fba2251d
resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 192Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 70
<<<<<<< HEAD

healthcheck:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
=======
image:
  repository: ghcr.io/arthur-16/argodemo
  digest: sha256:df089cfbc72adf0a2c5786c26d55a8ce5453645f2ef312fd63377ccd77ffc675
>>>>>>> 5acf6c8df5cce68fce1994debbd1a914fba2251d
