# Staging Environment - Production-like Configuration
replicaCount: 3
demo:
  message: "GitOps Demo - Staging Build 57f80b655c46"
  version: "staging-v1.1-57f80b655c46"
  environment: "staging"
ingress:
  host: demo-staging.local
resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 192Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 70
image:
  repository: ghcr.io/arthur-16/argodemo
  digest: sha256:df089cfbc72adf0a2c5786c26d55a8ce5453645f2ef312fd63377ccd77ffc675
