# Demo Application Configuration
# This file demonstrates GitOps principles with live updates

replicaCount: 1
maxReplicas: 10

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.21-alpine"

# Demo message displayed by the application
demo:
  message: "GitOps Demo - Default Environment"
  version: "v1.0"
  environment: "default"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: demo.local
  path: /
  pathType: Prefix

# Resource requests optimized for demo scaling
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Horizontal Pod Autoscaler for demo scaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Demo-friendly node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Health check configuration
healthcheck:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
