# Staging Environment - Working Configuration
replicaCount: 3
# Use working public image (CI can update this later)
image:
  repository: ghcr.io/arthur-16/argodemo
  tag: "1.21-alpine"
  digest: "sha256:d5bddc3f2b42beeab22a19cb8a2a6c91d123ea485dc52f8146ef3be38604e99c" # CI will populate this when your custom image is built
  pullPolicy: IfNotPresent
demo:
  message: "GitOps Demo - Staging Build 31a1237dba1b"
  version: "staging-v1.1-31a1237dba1b"
  environment: "staging"
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: demo-0-staging.local
  path: /
  pathType: Prefix
resources:
  requests:
    cpu: 75m
    memory: 96Mi
  limits:
    cpu: 150m
    memory: 192Mi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 70
healthcheck:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10
