# Development Environment - Optimized for Quick Changes
replicaCount: 2

demo:
  message: "GitOps Demo - Development Environment 🚀"
  version: "dev-v1.0"
  environment: "development"

ingress:
  host: demo-dev.local

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 60m
    memory: 64Mi

# Enable autoscaling for dev environment demos
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60
