version: '3.8'
services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: "local-dev"
        BUILD_TIME: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        GIT_SHA: "local"
    ports:
      - "8080:80"
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
