apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels: {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}         # 80
      targetPort: {{ .Values.containerPort }}  # 8080
  selector: {{- include "demo.selectorLabels" . | nindent 4 }}
