# Dev overlay. CI writes the immutable image digest here.
image:
  repository: ghcr.io/arthur-16/demo
  digest: "sha256:a82dc8d526bfcae61f9073c896c3c47962fa37b7ffcadacf04c022832905dacf"
replicaCount: 2
# For Minikube demo with NGINX ingress add-on
ingress:
  enabled: false
  className: nginx
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix
