# Dev overlay. CI writes the immutable image digest here.
image:
  repository: ghcr.io/arthur-16/argorepo
  digest: "sha256:5f05de49015718f68a9a3ac9a35d933e6e93160490e922f0af089917cc5b5470"
replicaCount: 2
# For Minikube demo with NGINX ingress add-on
ingress:
  enabled: false
  className: nginx
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix
