# Dev overlay. CI writes the immutable image digest here.
image:
  repository: ghcr.io/your-org/demo
  digest: "sha256:REPLACED_BY_CI"

replicaCount: 2

# For Minikube demo with NGINX ingress add-on
ingress:
  enabled: false
  className: nginx
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix
