name: build-and-pin
on:
  push:
    branches: [ main ]   # adjust as needed

permissions:
  contents: write    # to commit values-dev.yaml
  packages: write    # to push image to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        run: |
          set -euo pipefail
          COMMIT_SHA="$(git rev-parse --short=12 HEAD)"
          REPO="ghcr.io/${{ github.repository_owner }}/demo"
          IMAGE="${REPO}:${COMMIT_SHA}"
          docker build -t "${IMAGE}" .
          docker push "${IMAGE}"

          # Resolve digest
          DIGEST="$(docker buildx imagetools inspect ${IMAGE} \
            | awk -F': ' '/Digest:/ {print $2; exit}')"

          echo "Resolved digest: ${DIGEST}"

          # Update Helm values overlay
          pipx install yq || pip install yq || true
          yq -i ".image.digest = \"${DIGEST}\"" demo/values-dev.yaml

          git config user.name  "ci-bot"
          git config user.email "ci@example.com"
          git commit -am "Pin image to ${DIGEST}"
          git push
